package de.pietsch.generiert;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-19T14:33:18.963+02:00
 * Generated source version: 3.5.2
 *
 */
@WebServiceClient(name = "EmployeeService",
                  wsdlLocation = "file:/C:/Users/User/IdeaProjects/web-service-test/src/main/resources/EmployeeService.wsdl",
                  targetNamespace = "http://www.jpworks.com/employee")
public class EmployeeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.jpworks.com/employee", "EmployeeService");
    public final static QName EmployeeServiceSOAP = new QName("http://www.jpworks.com/employee", "EmployeeServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/User/IdeaProjects/web-service-test/src/main/resources/EmployeeService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EmployeeService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/User/IdeaProjects/web-service-test/src/main/resources/EmployeeService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EmployeeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmployeeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EmployeeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EmployeeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EmployeeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EmployeeServicePortType
     */
    @WebEndpoint(name = "EmployeeServiceSOAP")
    public EmployeeServicePortType getEmployeeServiceSOAP() {
        return super.getPort(EmployeeServiceSOAP, EmployeeServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeServicePortType
     */
    @WebEndpoint(name = "EmployeeServiceSOAP")
    public EmployeeServicePortType getEmployeeServiceSOAP(WebServiceFeature... features) {
        return super.getPort(EmployeeServiceSOAP, EmployeeServicePortType.class, features);
    }

}
